catalog/config/routes.rb
Rails.application.routes.draw do
  resources :books
end

catalog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

catalog/app/models/book.rb
class Book < ApplicationRecord
end

catalog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

catalog/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end
  
  def new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to @book
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to @book
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :author)
  end
end

catalog/app/helpers/application_helper.rb
module ApplicationHelper
end

catalog/app/helpers/books_helper.rb
module BooksHelper
end

catalog/app/views/books/edit.html.erb
<h1>Atualização de Livro</h1>
<%= form_for :book, url: book_path(@book), method: :patch do |b| %>
<ul>
  <li>
    <%= b.label :title %>
    <%= b.text_field :title %>
  </li>
  <li>
    <%= b.label :author %>
    <%= b.text_field :author %>
  </li>
</ul>
<%= b.submit %>
<% end %>

catalog/app/views/books/index.html.erb
<h1>Todos os livros</h1>

<ul>
  <% @books.each do |book| %>
  <li>
    <%= book.title %> de <%= book.author %>
    <%= link_to 'Editar', edit_book_path(book) %>
    <%= link_to 'Remover', book_path(book), method: :delete, data: { confirm: "Tem certeza?" } %>
  </li>
  <% end %>
</ul>

catalog/app/views/books/new.html.erb
<h1>Novo Livro</h1>
<%= form_for :book, url: books_path do |b| %>
<ul>
  <li>
    <%= b.label :title %>
    <%= b.text_field :title %>
  </li>
  <li>
    <%= b.label :author %>
    <%= b.text_field :author %>
  </li>
</ul>
<%= b.submit %>
<% end %>

catalog/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h2><%= @book.author %></h2> 

catalog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catalog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>